version: "2.4"
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - vol-prom-data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - net-metrics
      
volumes:
  vol-prom-data:

networks:
  net-metrics: # class B network-metrics
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
